import { MemoryOption } from '@interfaces/memory.interfaces';

const memoryOptions: MemoryOption[] = [
  {
    id: 'familia',
    option: 'Familia',
    people: [
      { name: 'Aita', img: '/memory/img/aita.png' },
      { name: 'Ama', img: '/memory/img/ama.png' },
      { name: 'Abuela', img: '/memory/img/abuela.png' },
      { name: 'Abuelo', img: '/memory/img/abuelo.png' },
      { name: 'Izeko Amaia', img: '/memory/img/izeko-amaia.png' },
      { name: 'Amama', img: '/memory/img/amama.png' },
      { name: 'Aitxitxa', img: '/memory/img/aitxitxa.png' },
      { name: 'Tia Piti', img: '/memory/img/tia-piti.png' },
      { name: 'Tio Imanol', img: '/memory/img/tio-imanol.png' },
      { name: 'Tia Eider', img: '/memory/img/tia-eider.png' },
      { name: 'Tia Itxi', img: '/memory/img/tia-itxi.png' },
    ],
  },
  {
    id: 'eneko',
    option: 'Eneko',
    people: [
      { name: 'Adrian', img: '/txartelak/eneko/adrian.webp' },
      { name: 'Ager', img: '/txartelak/eneko/ager.webp' },
      { name: 'Aimar', img: '/txartelak/eneko/aimar.webp' },
      { name: 'Ander Xabier', img: '/txartelak/eneko/ander-xabier.webp' },
      { name: 'Aratz', img: '/txartelak/eneko/aratz.webp' },
      { name: 'Arya', img: '/txartelak/eneko/arya.webp' },
      { name: 'Beñat', img: '/txartelak/eneko/benat.webp' },
      { name: 'Eider', img: '/txartelak/eneko/eider.webp' },
      { name: 'Eneko', img: '/txartelak/eneko/eneko.webp' },
      { name: 'Enetz', img: '/txartelak/eneko/enetz.webp' },
      { name: 'Harri', img: '/txartelak/eneko/harri.webp' },
      { name: 'Hodei', img: '/txartelak/eneko/hodei.webp' },
      { name: 'Irati', img: '/txartelak/eneko/irati.webp' },
      { name: 'Izadi', img: '/txartelak/eneko/izadi.webp' },
      { name: 'Izane', img: '/txartelak/eneko/izane.webp' },
      { name: 'Izare', img: '/txartelak/eneko/izare.webp' },
      { name: 'Jare', img: '/txartelak/eneko/jare.webp' },
      { name: 'Joaquin', img: '/txartelak/eneko/joaquin.webp' },
      { name: 'Julen', img: '/txartelak/eneko/julen.webp' },
      { name: 'Luken', img: '/txartelak/eneko/luken.webp' },
      { name: 'Maialen', img: '/txartelak/eneko/maialen.webp' },
      { name: 'Malen', img: '/txartelak/eneko/malen.webp' },
      { name: 'Mikel', img: '/txartelak/eneko/mikel.webp' },
      { name: 'Nahia', img: '/txartelak/eneko/nahia.webp' },
      { name: 'Ninbe', img: '/txartelak/eneko/ninbe.webp' },
      { name: 'Paul', img: '/txartelak/eneko/paul.webp' },
    ],
  },
  {
    id: 'unai',
    option: 'Unai',
    people: [
      { name: 'Aiora', img: '/txartelak/unai/aiora.webp' },
      { name: 'Aiur', img: '/txartelak/unai/aiur.webp' },
      { name: 'Alaia', img: '/txartelak/unai/alaia.webp' },
      { name: 'Amets', img: '/txartelak/unai/amets.webp' },
      { name: 'Ane', img: '/txartelak/unai/ane.webp' },
      { name: 'Ariane', img: '/txartelak/unai/ariane.webp' },
      { name: 'Ekia', img: '/txartelak/unai/ekia.webp' },
      { name: 'Enara', img: '/txartelak/unai/enara.webp' },
      { name: 'Enzo', img: '/txartelak/unai/enzo.webp' },
      { name: 'Euken', img: '/txartelak/unai/euken.webp' },
      { name: 'Haizea', img: '/txartelak/unai/haizea.webp' },
      { name: 'Inari', img: '/txartelak/unai/inari.webp' },
      { name: 'Jon', img: '/txartelak/unai/jon.webp' },
      { name: 'June', img: '/txartelak/unai/june.webp' },
      { name: 'Katixa', img: '/txartelak/unai/katixa.webp' },
      { name: 'Lier', img: '/txartelak/unai/lier.webp' },
      { name: 'Markel', img: '/txartelak/unai/markel.webp' },
      { name: 'Martina', img: '/txartelak/unai/martina.webp' },
      { name: 'Naia', img: '/txartelak/unai/naia.webp' },
      { name: 'Oier', img: '/txartelak/unai/oier.webp' },
      { name: 'Oinatz', img: '/txartelak/unai/oinatz.webp' },
      { name: 'Roke', img: '/txartelak/unai/roke.webp' },
      { name: 'Unai', img: '/txartelak/unai/unai.webp' },
      { name: 'Unax', img: '/txartelak/unai/unax.webp' },
      { name: 'Xabier', img: '/txartelak/unai/xabier.webp' },
    ],
  },
];

export default memoryOptions;
