export const METRO_DATA = {
  bilbao: {
    ciudad: 'Bilbao',
    lineas: [
      {
        num: 1,
        inicio: 34,
        fin: 18,
        color: 'e74f1e',
        colorTexto: 'ffffff',
        paradas: [
          34, 45, 42, 26, 13, 21, 14, 4, 3, 31, 19, 6, 25, 27, 8, 17, 28, 36,
          40, 16, 37, 22, 30, 1, 47, 39, 11, 15, 18,
        ],
      },
      {
        num: 2,
        inicio: 23,
        fin: 12,
        color: '000000',
        colorTexto: 'ffffff',
        paradas: [
          23, 38, 33, 35, 2, 41, 44, 9, 10, 5, 20, 36, 40, 16, 37, 22, 30, 1,
          47, 39, 11, 15, 18, 7, 12,
        ],
      },
      {
        num: 3,
        inicio: 29,
        fin: 24,
        color: 'e0007a',
        colorTexto: 'ffffff',
        paradas: [29, 46, 47, 48, 43, 32, 24],
      },
    ],
    paradas: [
      {
        id: 1,
        nombre: 'Abando',
        correspondencia: [1, 2],
      },
      {
        id: 2,
        nombre: 'Abatxolo',
        correspondencia: [2],
      },
      {
        id: 3,
        nombre: 'Aiboa',
        correspondencia: [1],
      },
      {
        id: 4,
        nombre: 'Algorta',
        correspondencia: [1],
      },
      {
        id: 5,
        nombre: 'Ansio',
        correspondencia: [2],
      },
      {
        id: 6,
        nombre: 'Areeta',
        correspondencia: [1],
      },
      {
        id: 7,
        nombre: 'Ariz',
        correspondencia: [2],
      },
      {
        id: 8,
        nombre: 'Astrabudua',
        correspondencia: [1],
      },
      {
        id: 9,
        nombre: 'Bagatza',
        correspondencia: [2],
      },
      {
        id: 10,
        nombre: 'Barakaldo',
        correspondencia: [2],
      },
      {
        id: 11,
        nombre: 'Basarrate',
        correspondencia: [1, 2],
      },
      {
        id: 12,
        nombre: 'Basauri',
        correspondencia: [2],
      },
      {
        id: 13,
        nombre: 'Berango',
        correspondencia: [1],
      },
      {
        id: 14,
        nombre: 'Bidezabal',
        correspondencia: [1],
      },
      {
        id: 15,
        nombre: 'Bolueta',
        correspondencia: [1, 2],
      },
      {
        id: 16,
        nombre: 'Deustu',
        correspondencia: [1, 2],
      },
      {
        id: 17,
        nombre: 'Erandio',
        correspondencia: [1],
      },
      {
        id: 18,
        nombre: 'Etxebarri',
        correspondencia: [1, 2],
      },
      {
        id: 19,
        nombre: 'Gobela',
        correspondencia: [1],
      },
      {
        id: 20,
        nombre: 'Gurutzeta - Cruces',
        correspondencia: [2],
      },
      {
        id: 21,
        nombre: 'Ibarbengoa',
        correspondencia: [1],
      },
      {
        id: 22,
        nombre: 'Indautxu',
        correspondencia: [1, 2],
      },
      {
        id: 23,
        nombre: 'Kabiezes',
        correspondencia: [2],
      },
      {
        id: 24,
        nombre: 'Kukullaga',
        correspondencia: [3],
      },
      {
        id: 25,
        nombre: 'Lamiako',
        correspondencia: [1],
      },
      {
        id: 26,
        nombre: 'Larrabasterra',
        correspondencia: [1],
      },
      {
        id: 27,
        nombre: 'Leioa',
        correspondencia: [1],
      },
      {
        id: 28,
        nombre: 'Lutxana',
        correspondencia: [1],
      },
      {
        id: 29,
        nombre: 'Matiko',
        correspondencia: [3],
      },
      {
        id: 30,
        nombre: 'Moyua',
        correspondencia: [1, 2],
      },
      {
        id: 31,
        nombre: 'Neguri',
        correspondencia: [1],
      },
      {
        id: 32,
        nombre: 'Otxarkoaga',
        correspondencia: [3],
      },
      {
        id: 33,
        nombre: 'Peñota',
        correspondencia: [2],
      },
      {
        id: 34,
        nombre: 'Plentzia',
        correspondencia: [1],
      },
      {
        id: 35,
        nombre: 'Portugalete',
        correspondencia: [2],
      },
      {
        id: 36,
        nombre: 'San Ignazio',
        correspondencia: [1, 2],
      },
      {
        id: 37,
        nombre: 'Santimami - San Mamés',
        correspondencia: [1, 2],
      },
      {
        id: 38,
        nombre: 'Santurtzi',
        correspondencia: [2],
      },
      {
        id: 39,
        nombre: 'Santutxu',
        correspondencia: [1, 2],
      },
      {
        id: 40,
        nombre: 'Sarriko',
        correspondencia: [1, 2],
      },
      {
        id: 41,
        nombre: 'Sestao',
        correspondencia: [2],
      },
      {
        id: 42,
        nombre: 'Sopela',
        correspondencia: [1],
      },
      {
        id: 43,
        nombre: 'Txurdinaga',
        correspondencia: [3],
      },
      {
        id: 44,
        nombre: 'Urbinaga',
        correspondencia: [2],
      },
      {
        id: 45,
        nombre: 'Urduliz',
        correspondencia: [1],
      },
      {
        id: 46,
        nombre: 'Uribarri',
        correspondencia: [3],
      },
      {
        id: 47,
        nombre: 'Zazpikaleak - Casco Viejo',
        correspondencia: [1, 2, 3],
      },
      {
        id: 48,
        nombre: 'Zurbaranbarri',
        correspondencia: [3],
      },
    ],
  },
  madrid: {
    ciudad: 'Madrid',
    lineas: [
      {
        num: 1,
        inicio: 172,
        fin: 229,
        color: '2bb6e6',
        colorTexto: 'ffffff',
        paradas: [
          172, 33, 55, 177, 227, 219, 85, 16, 69, 196, 108, 42, 223, 95, 217,
          220, 17, 83, 27, 146, 160, 186, 153, 180, 43, 14, 147, 215, 237, 65,
          117, 129, 229,
        ],
      },
      {
        num: 2,
        inicio: 'Las Rosas',
        fin: 'Cuatro Caminos',
        color: 'eb2f29',
        colorTexto: 'ffffff',
        paradas: [
          'Las Rosas',
          'Av. de Guadalajara',
          'Alsacia',
          'La Almudena',
          'La Elipa',
          'Ventas',
          'Manuel Becerra',
          'Goya',
          'Príncipe de Vergara',
          'Retiro',
          'Banco de España',
          'Sevilla',
          'Sol',
          'Callao',
          'Santo Domingo',
          'Noviciado',
          'San Bernardo',
          'Quevedo',
          'Canal',
          'Cuatro Caminos',
        ],
      },
      {
        num: 3,
        inicio: 'Villaverde Alto',
        fin: 'Moncloa',
        color: 'fed105',
        colorTexto: '015396',
        paradas: [
          'Villaverde Alto',
          'San Cristóbal',
          'Villaverde Bajo-Cruce',
          'Ciudad de los Ángeles',
          'Ciudad de los Ángeles',
          'Hospital 12 de Octubre',
          'Almendrales',
          'Legazpi',
          'Delicias',
          'Palos de la Frontera',
          'Embajadores',
          'Lavapiés',
          'Sol',
          'Callao',
          'Plaza de España',
          'Ventura Rodríguez',
          'Argüelles',
          'Moncloa',
        ],
      },
      {
        num: 4,
        inicio: 'Argüelles',
        fin: 'Pinar de Chamartín',
        color: 'a15c2f',
        colorTexto: 'ffffff',
        paradas: [
          'Argüelles',
          'San Bernardo',
          'Bilbao',
          'Alonso Martínez',
          'Colón',
          'Serrano',
          'Velázquez',
          'Goya',
          'Lista',
          'Diego de León',
          'Av. de América',
          'Prosperidad',
          'Alfonso XIII',
          'Av. de la Paz',
          'Arturo Soria',
          'Esperanza',
          'Canillas',
          'Mar de Cristal',
          'San Lorenzo',
          'Parque de Santa María',
          'Hortaleza',
          'Manoteras',
          'Pinar de Chamartín',
        ],
      },
      {
        num: 5,
        inicio: 'Alameda de Osuna',
        fin: 'Casa de Campo',
        color: '7ac142',
        colorTexto: 'ffffff',
        paradas: [
          'Alameda de Osuna',
          'El Capricho',
          'Canillejas',
          'Torre Arias',
          'Suanzes',
          'Ciudad Lineal',
          'Pueblo Nuevo',
          'Quintana',
          'El Carmen',
          'Ventas',
          'Diego de León',
          'Núñez de Balboa',
          'Rubén Darío',
          'Alonso Martínez',
          'Chueca',
          'Gran Vía',
          'Callao',
          'Ópera',
          'La Latina',
          'Puerta de Toledo',
          'Acacias',
          'Pirámides',
          'Marqués de Vadillo',
          'Urgel',
          'Oporto',
          'Vista Alegre',
          'Carabanchel',
          'Eugenia de Montijo',
          'Aluche',
          'Empalme',
          'Campamento',
          'Casa de Campo',
        ],
      },
      {
        num: 6,
        inicio: 'Circular',
        fin: 'Circular',
        color: '737f86',
        colorTexto: 'ffffff',
        paradas: [
          'Príncipe Pío',
          'Puerta del Ángel',
          'Alto de Extremadura',
          'Lucero',
          'Laguna',
          'Carpetana',
          'Oporto',
          'Opañel',
          'Plaza Elíptica',
          'Usera',
          'Legazpi',
          'Arganzuela Planetario',
          'Méndez Álvaro',
          'Pacífico',
          'Conde de Casal',
          'Sainz de Baranda',
          'O’Donnell',
          'Manuel Becerra',
          'Diego de León',
          'Av. de América',
          'República Argentina',
          'Nuevos Ministerios',
          'Cuatro Caminos',
          'Guzmán el Bueno',
          'Vicente Aleixandre',
          'Ciudad Universitaria',
          'Moncloa',
          'Argüelles',
        ],
      },
      {
        num: 7,
        inicio: 'Hospital del Henares',
        fin: 'Pitis',
        color: 'f79727',
        colorTexto: 'ffffff',
        paradas: [
          'Hospital del Henares',
          'Henares',
          'Jarama',
          'San Fernando',
          'La Rambla',
          'Coslada Central',
          'Barrio del Puerto',
          'Estadio Metropolitano',
          'Las Musas',
          'San Blas',
          'Simancas',
          'García Noblejas',
          'Ascao',
          'Pueblo Nuevo',
          'Barrio de la Concepción',
          'Parque de las Avenidas',
          'Cartagena',
          'Av. de América',
          'Gregorio Marañón',
          'Alonso Cano',
          'Canal',
          'Islas Filipinas',
          'Guzmán el Bueno',
          'Francos Rodríguez',
          'Valdezarza',
          'Antonio Machado',
          'Peñagrande',
          'Av. de la Ilustración',
          'Lacoma',
          'Arroyofresno',
          'Pitis',
        ],
      },
      {
        num: 8,
        inicio: 'Nuevos Ministerios',
        fin: 'Aeropuerto T4',
        color: 'db74ae',
        colorTexto: 'ffffff',
        paradas: [
          'Nuevos Ministerios',
          'Colombia',
          'Pinar del Rey',
          'Mar de Cristal',
          'Feria de Madrid',
          'Aeropuerto T1-T2-T3',
          'Barajas',
          'Aeropuerto T4',
        ],
      },
      {
        num: 9,
        inicio: 'Paco de Lucía',
        fin: 'Arganda del Rey',
        color: '9c3293',
        colorTexto: 'ffffff',
        paradas: [
          'Paco de Lucía',
          'Mirasierra',
          'Herrera Oria',
          'Barrio del Pilar',
          'Ventilla',
          'Plaza de Castilla',
          'Duque de Pastrana',
          'Pío XII',
          'Colombia',
          'Concha Espina',
          'Cruz del Rayo',
          'Av. de América',
          'Núñez de Balboa',
          'Príncipe de Vergara',
          'Ibiza',
          'Sainz de Baranda',
          'Estrella',
          'Vinateros',
          'Artilleros',
          'Pavones',
          'Valdebernardo',
          'Vicálvaro',
          'San Cipriano',
          'Puerta de Arganda',
          'Rivas-Urbanizaciones',
          'Rivas Futura',
          'Rivas Vaciamadrid',
          'La Poveda',
          'Arganda del Rey',
        ],
      },
      {
        num: 10,
        inicio: 'Hospital Infanta Sofía',
        fin: 'Puerta del Sur',
        color: '015396',
        colorTexto: 'ffffff',
        paradas: [
          'Hospital Infanta Sofía',
          'Reyes Católicos',
          'Baunatal',
          'Manuel de Falla',
          'Marqués de la Valdavia',
          'La Moraleja',
          'La Granja',
          'Ronda de la Comunicación',
          'Las Tablas',
          'Montecarmelo',
          'Tres Olivos',
          'Fuencarral',
          'Begoña',
          'Chamartín',
          'Plaza de Castilla',
          'Cuzco',
          'Santiago Bernabéu',
          'Nuevos Ministerios',
          'Gregorio Marañón',
          'Alonso Martínez',
          'Tribunal',
          'Plaza de España',
          'Príncipe Pío',
          'Lago',
          'Batán',
          'Casa de Campo',
          'Colonia Jardín',
          'Aviación Española',
          'Cuatro Vientos',
          'Joaquín Vilumbrales',
          'Puerta del Sur',
        ],
      },
      {
        num: 11,
        inicio: 'Plaza Elíptica',
        fin: 'La Fortuna',
        color: '00a94e',
        colorTexto: 'ffffff',
        paradas: [
          'Plaza Elíptica',
          'Abrantes',
          'Pan Bendito',
          'San Francisco',
          'Carabanchel Alto',
          'La Peseta',
          'La Fortuna',
        ],
      },
      {
        num: 12,
        inicio: 'MetroSur',
        fin: 'MetroSur',
        color: 'a49901',
        colorTexto: 'ffffff',
        paradas: [
          'Puerta del Sur',
          'Parque Lisboa',
          'AlcorcónCentral',
          'Parque Oeste',
          'Universidad Rey Juan Carlos',
          'Móstoles Central',
          'Pradillo',
          'Hospital de Móstoles',
          'Manuela Malasaña',
          'Loranca',
          'Hospital de Fuenlabrada',
          'Parque Europa',
          'Fuenlabrada Central',
          'Parque de los Estados',
          'Arroyo Culebro',
          'Conservatorio',
          'Alonso de Mendoza',
          'Getafe Central',
          'Juan de la Cierva',
          'El Casar',
          'Los Espartales',
          'El Bercial',
          'El Carrascal',
          'Julián Besteiro',
          'Casa del Reloj',
          'Hospital Severo Ochoa',
          'Leganés Central',
          'San Nicasio',
        ],
      },
    ],
    paradas: [
      {
        id: 1,
        nombre: 'Abrantes',
        correspondencia: [],
      },
      {
        id: 2,
        nombre: 'Acacias',
        correspondencia: [],
      },
      {
        id: 3,
        nombre: 'Aeropuerto T1-T2-T3',
        correspondencia: [],
      },
      {
        id: 4,
        nombre: 'Aeropuerto T4',
        correspondencia: [],
      },
      {
        id: 5,
        nombre: 'Alameda de Osuna',
        correspondencia: [],
      },
      {
        id: 6,
        nombre: 'AlcorcónCentral',
        correspondencia: [],
      },
      {
        id: 7,
        nombre: 'Alfonso XIII',
        correspondencia: [],
      },
      {
        id: 8,
        nombre: 'Almendrales',
        correspondencia: [],
      },
      {
        id: 9,
        nombre: 'Alonso Cano',
        correspondencia: [],
      },
      {
        id: 10,
        nombre: 'Alonso de Mendoza',
        correspondencia: [],
      },
      {
        id: 11,
        nombre: 'Alonso Martínez',
        correspondencia: [],
      },
      {
        id: 12,
        nombre: 'Alsacia',
        correspondencia: [],
      },
      {
        id: 13,
        nombre: 'Alto de Extremadura',
        correspondencia: [],
      },
      {
        id: 14,
        nombre: 'Alto del Arenal',
        correspondencia: [1],
      },
      {
        id: 15,
        nombre: 'Aluche',
        correspondencia: [],
      },
      {
        id: 16,
        nombre: 'Alvarado',
        correspondencia: [1],
      },
      {
        id: 17,
        nombre: 'Antón Martín',
        correspondencia: [1],
      },
      {
        id: 18,
        nombre: 'Antonio Machado',
        correspondencia: [],
      },
      {
        id: 19,
        nombre: 'Arganda del Rey',
        correspondencia: [],
      },
      {
        id: 20,
        nombre: 'Arganzuela Planetario',
        correspondencia: [],
      },
      {
        id: 21,
        nombre: 'Argüelles',
        correspondencia: [],
      },
      {
        id: 22,
        nombre: 'Arroyo Culebro',
        correspondencia: [],
      },
      {
        id: 23,
        nombre: 'Arroyofresno',
        correspondencia: [],
      },
      {
        id: 24,
        nombre: 'Artilleros',
        correspondencia: [],
      },
      {
        id: 25,
        nombre: 'Arturo Soria',
        correspondencia: [],
      },
      {
        id: 26,
        nombre: 'Ascao',
        correspondencia: [],
      },
      {
        id: 27,
        nombre: 'Atocha',
        correspondencia: [1],
      },
      {
        id: 28,
        nombre: 'Av. de América',
        correspondencia: [],
      },
      {
        id: 29,
        nombre: 'Av. de Guadalajara',
        correspondencia: [],
      },
      {
        id: 30,
        nombre: 'Av. de la Ilustración',
        correspondencia: [],
      },
      {
        id: 31,
        nombre: 'Av. de la Paz',
        correspondencia: [],
      },
      {
        id: 32,
        nombre: 'Aviación Española',
        correspondencia: [],
      },
      {
        id: 33,
        nombre: 'Bambú',
        correspondencia: [1],
      },
      {
        id: 34,
        nombre: 'Banco de España',
        correspondencia: [],
      },
      {
        id: 35,
        nombre: 'Barajas',
        correspondencia: [],
      },
      {
        id: 36,
        nombre: 'Barrio de la Concepción',
        correspondencia: [],
      },
      {
        id: 37,
        nombre: 'Barrio del Pilar',
        correspondencia: [],
      },
      {
        id: 38,
        nombre: 'Barrio del Puerto',
        correspondencia: [],
      },
      {
        id: 39,
        nombre: 'Batán',
        correspondencia: [],
      },
      {
        id: 40,
        nombre: 'Baunatal',
        correspondencia: [],
      },
      {
        id: 41,
        nombre: 'Begoña',
        correspondencia: [],
      },
      {
        id: 42,
        nombre: 'Bilbao',
        correspondencia: [1, 4],
      },
      {
        id: 43,
        nombre: 'Buenos Aires',
        correspondencia: [1],
      },
      {
        id: 44,
        nombre: 'Callao',
        correspondencia: [],
      },
      {
        id: 45,
        nombre: 'Campamento',
        correspondencia: [],
      },
      {
        id: 46,
        nombre: 'Canal',
        correspondencia: [],
      },
      {
        id: 47,
        nombre: 'Canillas',
        correspondencia: [],
      },
      {
        id: 48,
        nombre: 'Canillejas',
        correspondencia: [],
      },
      {
        id: 49,
        nombre: 'Carabanchel',
        correspondencia: [],
      },
      {
        id: 50,
        nombre: 'Carabanchel Alto',
        correspondencia: [],
      },
      {
        id: 51,
        nombre: 'Carpetana',
        correspondencia: [],
      },
      {
        id: 52,
        nombre: 'Cartagena',
        correspondencia: [],
      },
      {
        id: 53,
        nombre: 'Casa de Campo',
        correspondencia: [],
      },
      {
        id: 54,
        nombre: 'Casa del Reloj',
        correspondencia: [],
      },
      {
        id: 55,
        nombre: 'Chamartín',
        correspondencia: [1, 10],
      },
      {
        id: 56,
        nombre: 'Chueca',
        correspondencia: [],
      },
      {
        id: 57,
        nombre: 'Ciudad de los Ángeles',
        correspondencia: [],
      },
      {
        id: 58,
        nombre: 'Ciudad Lineal',
        correspondencia: [],
      },
      {
        id: 59,
        nombre: 'Ciudad Universitaria',
        correspondencia: [],
      },
      {
        id: 60,
        nombre: 'Colombia',
        correspondencia: [],
      },
      {
        id: 61,
        nombre: 'Colón',
        correspondencia: [],
      },
      {
        id: 62,
        nombre: 'Colonia Jardín',
        correspondencia: [],
      },
      {
        id: 63,
        nombre: 'Concha Espina',
        correspondencia: [],
      },
      {
        id: 64,
        nombre: 'Conde de Casal',
        correspondencia: [],
      },
      {
        id: 65,
        nombre: 'Congosto',
        correspondencia: [1],
      },
      {
        id: 66,
        nombre: 'Conservatorio',
        correspondencia: [],
      },
      {
        id: 67,
        nombre: 'Coslada Central',
        correspondencia: [],
      },
      {
        id: 68,
        nombre: 'Cruz del Rayo',
        correspondencia: [],
      },
      {
        id: 69,
        nombre: 'Cuatro Caminos',
        correspondencia: [1, 2, 6],
      },
      {
        id: 70,
        nombre: 'Cuatro Vientos',
        correspondencia: [],
      },
      {
        id: 71,
        nombre: 'Cuzco',
        correspondencia: [],
      },
      {
        id: 72,
        nombre: 'Delicias',
        correspondencia: [],
      },
      {
        id: 73,
        nombre: 'Diego de León',
        correspondencia: [],
      },
      {
        id: 74,
        nombre: 'Duque de Pastrana',
        correspondencia: [],
      },
      {
        id: 75,
        nombre: 'El Bercial',
        correspondencia: [],
      },
      {
        id: 76,
        nombre: 'El Capricho',
        correspondencia: [],
      },
      {
        id: 77,
        nombre: 'El Carmen',
        correspondencia: [],
      },
      {
        id: 78,
        nombre: 'El Carrascal',
        correspondencia: [],
      },
      {
        id: 79,
        nombre: 'El Casar',
        correspondencia: [],
      },
      {
        id: 80,
        nombre: 'Embajadores',
        correspondencia: [],
      },
      {
        id: 81,
        nombre: 'Empalme',
        correspondencia: [],
      },
      {
        id: 82,
        nombre: 'Esperanza',
        correspondencia: [],
      },
      {
        id: 83,
        nombre: 'Estación del Arte',
        correspondencia: [1],
      },
      {
        id: 84,
        nombre: 'Estadio Metropolitano',
        correspondencia: [],
      },
      {
        id: 85,
        nombre: 'Estrecho',
        correspondencia: [1],
      },
      {
        id: 86,
        nombre: 'Estrella',
        correspondencia: [],
      },
      {
        id: 87,
        nombre: 'Eugenia de Montijo',
        correspondencia: [],
      },
      {
        id: 88,
        nombre: 'Feria de Madrid',
        correspondencia: [],
      },
      {
        id: 89,
        nombre: 'Francos Rodríguez',
        correspondencia: [],
      },
      {
        id: 90,
        nombre: 'Fuencarral',
        correspondencia: [],
      },
      {
        id: 91,
        nombre: 'Fuenlabrada Central',
        correspondencia: [],
      },
      {
        id: 92,
        nombre: 'García Noblejas',
        correspondencia: [],
      },
      {
        id: 93,
        nombre: 'Getafe Central',
        correspondencia: [],
      },
      {
        id: 94,
        nombre: 'Goya',
        correspondencia: [],
      },
      {
        id: 95,
        nombre: 'Gran Vía',
        correspondencia: [1, 5],
      },
      {
        id: 96,
        nombre: 'Gregorio Marañón',
        correspondencia: [],
      },
      {
        id: 97,
        nombre: 'Guzmán el Bueno',
        correspondencia: [],
      },
      {
        id: 98,
        nombre: 'Henares',
        correspondencia: [],
      },
      {
        id: 99,
        nombre: 'Herrera Oria',
        correspondencia: [],
      },
      {
        id: 100,
        nombre: 'Hortaleza',
        correspondencia: [],
      },
      {
        id: 101,
        nombre: 'Hospital 12 de Octubre',
        correspondencia: [],
      },
      {
        id: 102,
        nombre: 'Hospital de Fuenlabrada',
        correspondencia: [],
      },
      {
        id: 103,
        nombre: 'Hospital de Móstoles',
        correspondencia: [],
      },
      {
        id: 104,
        nombre: 'Hospital del Henares',
        correspondencia: [],
      },
      {
        id: 105,
        nombre: 'Hospital Infanta Sofía',
        correspondencia: [],
      },
      {
        id: 106,
        nombre: 'Hospital Severo Ochoa',
        correspondencia: [],
      },
      {
        id: 107,
        nombre: 'Ibiza',
        correspondencia: [],
      },
      {
        id: 108,
        nombre: 'Iglesia',
        correspondencia: [1],
      },
      {
        id: 109,
        nombre: 'Islas Filipinas',
        correspondencia: [],
      },
      {
        id: 110,
        nombre: 'Jarama',
        correspondencia: [],
      },
      {
        id: 111,
        nombre: 'Joaquín Vilumbrales',
        correspondencia: [],
      },
      {
        id: 112,
        nombre: 'Juan de la Cierva',
        correspondencia: [],
      },
      {
        id: 113,
        nombre: 'Julián Besteiro',
        correspondencia: [],
      },
      {
        id: 114,
        nombre: 'La Almudena',
        correspondencia: [],
      },
      {
        id: 115,
        nombre: 'La Elipa',
        correspondencia: [],
      },
      {
        id: 116,
        nombre: 'La Fortuna',
        correspondencia: [],
      },
      {
        id: 117,
        nombre: 'La Gavia',
        correspondencia: [1],
      },
      {
        id: 118,
        nombre: 'La Granja',
        correspondencia: [],
      },
      {
        id: 119,
        nombre: 'La Latina',
        correspondencia: [],
      },
      {
        id: 120,
        nombre: 'La Moraleja',
        correspondencia: [],
      },
      {
        id: 121,
        nombre: 'La Peseta',
        correspondencia: [],
      },
      {
        id: 122,
        nombre: 'La Poveda',
        correspondencia: [],
      },
      {
        id: 123,
        nombre: 'La Rambla',
        correspondencia: [],
      },
      {
        id: 124,
        nombre: 'Lacoma',
        correspondencia: [],
      },
      {
        id: 125,
        nombre: 'Lago',
        correspondencia: [],
      },
      {
        id: 126,
        nombre: 'Laguna',
        correspondencia: [],
      },
      {
        id: 127,
        nombre: 'Las Musas',
        correspondencia: [],
      },
      {
        id: 128,
        nombre: 'Las Rosas',
        correspondencia: [],
      },
      {
        id: 129,
        nombre: 'Las Suertes',
        correspondencia: [1],
      },
      {
        id: 130,
        nombre: 'Las Tablas',
        correspondencia: [],
      },
      {
        id: 131,
        nombre: 'Lavapiés',
        correspondencia: [],
      },
      {
        id: 132,
        nombre: 'Leganés Central',
        correspondencia: [],
      },
      {
        id: 133,
        nombre: 'Legazpi',
        correspondencia: [],
      },
      {
        id: 134,
        nombre: 'Lista',
        correspondencia: [],
      },
      {
        id: 135,
        nombre: 'Loranca',
        correspondencia: [],
      },
      {
        id: 136,
        nombre: 'Los Espartales',
        correspondencia: [],
      },
      {
        id: 137,
        nombre: 'Lucero',
        correspondencia: [],
      },
      {
        id: 138,
        nombre: 'Manoteras',
        correspondencia: [],
      },
      {
        id: 139,
        nombre: 'Manuel Becerra',
        correspondencia: [],
      },
      {
        id: 140,
        nombre: 'Manuel de Falla',
        correspondencia: [],
      },
      {
        id: 141,
        nombre: 'Manuela Malasaña',
        correspondencia: [],
      },
      {
        id: 142,
        nombre: 'Mar de Cristal',
        correspondencia: [],
      },
      {
        id: 143,
        nombre: 'Marqués de la Valdavia',
        correspondencia: [],
      },
      {
        id: 144,
        nombre: 'Marqués de Vadillo',
        correspondencia: [],
      },
      {
        id: 145,
        nombre: 'Méndez Álvaro',
        correspondencia: [],
      },
      {
        id: 146,
        nombre: 'Menéndez Pelayo',
        correspondencia: [1],
      },
      {
        id: 147,
        nombre: 'Miguel Hernández',
        correspondencia: [1],
      },
      {
        id: 148,
        nombre: 'Mirasierra',
        correspondencia: [],
      },
      {
        id: 149,
        nombre: 'Moncloa',
        correspondencia: [],
      },
      {
        id: 150,
        nombre: 'Montecarmelo',
        correspondencia: [],
      },
      {
        id: 151,
        nombre: 'Móstoles Central',
        correspondencia: [],
      },
      {
        id: 152,
        nombre: 'Noviciado',
        correspondencia: [],
      },
      {
        id: 153,
        nombre: 'Nueva Numancia',
        correspondencia: [1],
      },
      {
        id: 154,
        nombre: 'Nuevos Ministerios',
        correspondencia: [],
      },
      {
        id: 155,
        nombre: 'Núñez de Balboa',
        correspondencia: [],
      },
      {
        id: 156,
        nombre: 'O’Donnell',
        correspondencia: [],
      },
      {
        id: 157,
        nombre: 'Opañel',
        correspondencia: [],
      },
      {
        id: 158,
        nombre: 'Ópera',
        correspondencia: [],
      },
      {
        id: 159,
        nombre: 'Oporto',
        correspondencia: [],
      },
      {
        id: 160,
        nombre: 'Pacífico',
        correspondencia: [1, 6],
      },
      {
        id: 161,
        nombre: 'Paco de Lucía',
        correspondencia: [],
      },
      {
        id: 162,
        nombre: 'Palos de la Frontera',
        correspondencia: [],
      },
      {
        id: 163,
        nombre: 'Pan Bendito',
        correspondencia: [],
      },
      {
        id: 164,
        nombre: 'Parque de las Avenidas',
        correspondencia: [],
      },
      {
        id: 165,
        nombre: 'Parque de los Estados',
        correspondencia: [],
      },
      {
        id: 166,
        nombre: 'Parque de Santa María',
        correspondencia: [],
      },
      {
        id: 167,
        nombre: 'Parque Europa',
        correspondencia: [],
      },
      {
        id: 168,
        nombre: 'Parque Lisboa',
        correspondencia: [],
      },
      {
        id: 169,
        nombre: 'Parque Oeste',
        correspondencia: [],
      },
      {
        id: 170,
        nombre: 'Pavones',
        correspondencia: [],
      },
      {
        id: 171,
        nombre: 'Peñagrande',
        correspondencia: [],
      },
      {
        id: 172,
        nombre: 'Pinar de Chamartín',
        correspondencia: [1, 4],
      },
      {
        id: 173,
        nombre: 'Pinar del Rey',
        correspondencia: [],
      },
      {
        id: 174,
        nombre: 'Pío XII',
        correspondencia: [],
      },
      {
        id: 175,
        nombre: 'Pirámides',
        correspondencia: [],
      },
      {
        id: 176,
        nombre: 'Pitis',
        correspondencia: [],
      },
      {
        id: 177,
        nombre: 'Plaza de Castilla',
        correspondencia: [1, 9, 10],
      },
      {
        id: 178,
        nombre: 'Plaza de España',
        correspondencia: [],
      },
      {
        id: 179,
        nombre: 'Plaza Elíptica',
        correspondencia: [],
      },
      {
        id: 180,
        nombre: 'Portazgo',
        correspondencia: [1],
      },
      {
        id: 181,
        nombre: 'Pradillo',
        correspondencia: [],
      },
      {
        id: 182,
        nombre: 'Príncipe de Vergara',
        correspondencia: [],
      },
      {
        id: 183,
        nombre: 'Príncipe Pío',
        correspondencia: [],
      },
      {
        id: 184,
        nombre: 'Prosperidad',
        correspondencia: [],
      },
      {
        id: 185,
        nombre: 'Pueblo Nuevo',
        correspondencia: [],
      },
      {
        id: 186,
        nombre: 'Puente de Vallecas',
        correspondencia: [1],
      },
      {
        id: 187,
        nombre: 'Puerta de Arganda',
        correspondencia: [],
      },
      {
        id: 188,
        nombre: 'Puerta de Toledo',
        correspondencia: [],
      },
      {
        id: 189,
        nombre: 'Puerta del Ángel',
        correspondencia: [],
      },
      {
        id: 190,
        nombre: 'Puerta del Sur',
        correspondencia: [],
      },
      {
        id: 191,
        nombre: 'Quevedo',
        correspondencia: [],
      },
      {
        id: 192,
        nombre: 'Quintana',
        correspondencia: [],
      },
      {
        id: 193,
        nombre: 'República Argentina',
        correspondencia: [],
      },
      {
        id: 194,
        nombre: 'Retiro',
        correspondencia: [],
      },
      {
        id: 195,
        nombre: 'Reyes Católicos',
        correspondencia: [],
      },
      {
        id: 196,
        nombre: 'Ríos Rosas',
        correspondencia: [1],
      },
      {
        id: 197,
        nombre: 'Rivas Futura',
        correspondencia: [],
      },
      {
        id: 198,
        nombre: 'Rivas Vaciamadrid',
        correspondencia: [],
      },
      {
        id: 199,
        nombre: 'Rivas-Urbanizaciones',
        correspondencia: [],
      },
      {
        id: 200,
        nombre: 'Ronda de la Comunicación',
        correspondencia: [],
      },
      {
        id: 201,
        nombre: 'Rubén Darío',
        correspondencia: [],
      },
      {
        id: 202,
        nombre: 'Sainz de Baranda',
        correspondencia: [],
      },
      {
        id: 203,
        nombre: 'San Bernardo',
        correspondencia: [],
      },
      {
        id: 204,
        nombre: 'San Blas',
        correspondencia: [],
      },
      {
        id: 205,
        nombre: 'San Cipriano',
        correspondencia: [],
      },
      {
        id: 206,
        nombre: 'San Cristóbal',
        correspondencia: [],
      },
      {
        id: 207,
        nombre: 'San Fernando',
        correspondencia: [],
      },
      {
        id: 208,
        nombre: 'San Francisco',
        correspondencia: [],
      },
      {
        id: 209,
        nombre: 'San Lorenzo',
        correspondencia: [],
      },
      {
        id: 210,
        nombre: 'San Nicasio',
        correspondencia: [],
      },
      {
        id: 211,
        nombre: 'Santiago Bernabéu',
        correspondencia: [],
      },
      {
        id: 212,
        nombre: 'Santo Domingo',
        correspondencia: [],
      },
      {
        id: 213,
        nombre: 'Serrano',
        correspondencia: [],
      },
      {
        id: 214,
        nombre: 'Sevilla',
        correspondencia: [],
      },
      {
        id: 215,
        nombre: 'Sierra de Guadalupe',
        correspondencia: [1],
      },
      {
        id: 216,
        nombre: 'Simancas',
        correspondencia: [],
      },
      {
        id: 217,
        nombre: 'Sol',
        correspondencia: [1, 2, 3],
      },
      {
        id: 218,
        nombre: 'Suanzes',
        correspondencia: [],
      },
      {
        id: 219,
        nombre: 'Tetuán',
        correspondencia: [1],
      },
      {
        id: 220,
        nombre: 'Tirso de Molina',
        correspondencia: [1],
      },
      {
        id: 221,
        nombre: 'Torre Arias',
        correspondencia: [],
      },
      {
        id: 222,
        nombre: 'Tres Olivos',
        correspondencia: [],
      },
      {
        id: 223,
        nombre: 'Tribunal',
        correspondencia: [1, 10],
      },
      {
        id: 224,
        nombre: 'Universidad Rey Juan Carlos',
        correspondencia: [],
      },
      {
        id: 225,
        nombre: 'Urgel',
        correspondencia: [],
      },
      {
        id: 226,
        nombre: 'Usera',
        correspondencia: [],
      },
      {
        id: 227,
        nombre: 'Valdeacederas',
        correspondencia: [1],
      },
      {
        id: 228,
        nombre: 'Valdebernardo',
        correspondencia: [],
      },
      {
        id: 229,
        nombre: 'Valdecarros',
        correspondencia: [1],
      },
      {
        id: 230,
        nombre: 'Valdezarza',
        correspondencia: [],
      },
      {
        id: 231,
        nombre: 'Velázquez',
        correspondencia: [],
      },
      {
        id: 232,
        nombre: 'Ventas',
        correspondencia: [],
      },
      {
        id: 233,
        nombre: 'Ventilla',
        correspondencia: [],
      },
      {
        id: 234,
        nombre: 'Ventura Rodríguez',
        correspondencia: [],
      },
      {
        id: 235,
        nombre: 'Vicálvaro',
        correspondencia: [],
      },
      {
        id: 236,
        nombre: 'Vicente Aleixandre',
        correspondencia: [],
      },
      {
        id: 237,
        nombre: 'Villa de Vallecas',
        correspondencia: [1],
      },
      {
        id: 238,
        nombre: 'Villaverde Alto',
        correspondencia: [],
      },
      {
        id: 239,
        nombre: 'Villaverde Bajo-Cruce',
        correspondencia: [],
      },
      {
        id: 240,
        nombre: 'Vinateros',
        correspondencia: [],
      },
      {
        id: 241,
        nombre: 'Vista Alegre',
        correspondencia: [],
      },
    ],
  },
};
