export const METRO_DATA = {
  bilbao: {
    ciudad: 'Bilbao',
    lineas: [
      {
        num: 1,
        inicio: 'Plentzia',
        fin: 'Etxebarri',
        color: 'e74f1e',
        colorTexto: 'ffffff',
        paradas: [
          'Plentzia',
          'Urduliz',
          'Sopela',
          'Larrabasterra',
          'Berango',
          'Ibarbengoa',
          'Bidezabal',
          'Algorta',
          'Aiboa',
          'Neguri',
          'Gobela',
          'Areeta',
          'Lamiako',
          'Leioa',
          'Astrabudua',
          'Erandio',
          'Lutxana',
          'San Ignazio',
          'Sarriko',
          'Deustu',
          'Santimami - San Mamés',
          'Indautxu',
          'Moyua',
          'Abando',
          'Zazpikaleak - Casco Viejo',
          'Santutxu',
          'Basarrate',
          'Bolueta',
          'Etxebarri',
        ],
      },
      {
        num: 2,
        inicio: 'Kabiezes',
        fin: 'Basauri',
        color: '000000',
        colorTexto: 'ffffff',
        paradas: [
          'Kabiezes',
          'Santurtzi',
          'Peñota',
          'Portugalete',
          'Abatxolo',
          'Sestao',
          'Urbinaga',
          'Bagatza',
          'Barakaldo',
          'Ansio',
          'Gurutzeta - Cruces',
          'San Ignazio',
          'Sarriko',
          'Deustu',
          'Santimami - San Mamés',
          'Indautxu',
          'Moyua',
          'Abando',
          'Zazpikaleak - Casco Viejo',
          'Santutxu',
          'Basarrate',
          'Bolueta',
          'Etxebarri',
          'Ariz',
          'Basauri',
        ],
      },
      {
        num: 3,
        inicio: 'Matiko',
        fin: 'Kukullaga',
        color: 'e0007a',
        colorTexto: 'ffffff',
        paradas: [
          'Matiko',
          'Uribarri',
          'Zazpikaleak - Casco Viejo',
          'Zurbaranbarri',
          'Txurdinaga',
          'Otxarkoaga',
          'Kukullaga',
        ],
      },
    ],
  },
  madrid: {
    ciudad: 'Madrid',
    lineas: [
      {
        num: 1,
        inicio: 'Pinar de Chamartín',
        fin: 'Valdecarros',
        color: '2bb6e6',
        colorTexto: 'ffffff',
        paradas: [
          'Pinar de Chamartín',
          'Bambú',
          'Chamartín',
          'Plaza de Castilla',
          'Valdeacederas',
          'Tetuán',
          'Estrecho',
          'Alvarado',
          'Cuatro Caminos',
          'Ríos Rosas',
          'Iglesia',
          'Bilbao',
          'Tribunal',
          'Gran Vía',
          'Sol',
          'Tirso de Molina',
          'Antón Martín',
          'Estación del Arte',
          'Atocha',
          'Menéndez Pelayo',
          'Pacífico',
          'Puente de Vallecas',
          'Nueva Numancia',
          'Portazgo',
          'Buenos Aires',
          'Alto del Arenal',
          'Miguel Hernández',
          'Sierra de Guadalupe',
          'Villa de Vallecas',
          'Congosto',
          'La Gavia',
          'Las Suertes',
          'Valdecarros',
        ],
      },
      {
        num: 2,
        inicio: 'Las Rosas',
        fin: 'Cuatro Caminos',
        color: 'eb2f29',
        colorTexto: 'ffffff',
        paradas: [
          'Las Rosas',
          'Av. de Guadalajara',
          'Alsacia',
          'La Almudena',
          'La Elipa',
          'Ventas',
          'Manuel Becerra',
          'Goya',
          'Príncipe de Vergara',
          'Retiro',
          'Banco de España',
          'Sevilla',
          'Sol',
          'Callao',
          'Santo Domingo',
          'Noviciado',
          'San Bernardo',
          'Quevedo',
          'Canal',
          'Cuatro Caminos',
        ],
      },
      {
        num: 3,
        inicio: 'Villaverde Alto',
        fin: 'Moncloa',
        color: 'fed105',
        colorTexto: '015396',
        paradas: [
          'Villaverde Alto',
          'San Cristóbal',
          'Villaverde Bajo-Cruce',
          'Ciudad de los Ángeles',
          'Ciudad de los Ángeles',
          'Hospital 12 de Octubre',
          'Almendrales',
          'Legazpi',
          'Delicias',
          'Palos de la Frontera',
          'Embajadores',
          'Lavapiés',
          'Sol',
          'Callao',
          'Plaza de España',
          'Ventura Rodríguez',
          'Argüelles',
          'Moncloa',
        ],
      },
      {
        num: 4,
        inicio: 'Argüelles',
        fin: 'Pinar de Chamartín',
        color: 'a15c2f',
        colorTexto: 'ffffff',
        paradas: [
          'Argüelles',
          'San Bernardo',
          'Bilbao',
          'Alonso Martínez',
          'Colón',
          'Serrano',
          'Velázquez',
          'Goya',
          'Lista',
          'Diego de León',
          'Av. de América',
          'Prosperidad',
          'Alfonso XIII',
          'Av. de la Paz',
          'Arturo Soria',
          'Esperanza',
          'Canillas',
          'Mar de Cristal',
          'San Lorenzo',
          'Parque de Santa María',
          'Hortaleza',
          'Manoteras',
          'Pinar de Chamartín',
        ],
      },
      {
        num: 5,
        inicio: 'Alameda de Osuna',
        fin: 'Casa de Campo',
        color: '7ac142',
        colorTexto: 'ffffff',
        paradas: [
          'Alameda de Osuna',
          'El Capricho',
          'Canillejas',
          'Torre Arias',
          'Suanzes',
          'Ciudad Lineal',
          'Pueblo Nuevo',
          'Quintana',
          'El Carmen',
          'Ventas',
          'Diego de León',
          'Núñez de Balboa',
          'Rubén Darío',
          'Alonso Martínez',
          'Chueca',
          'Gran Vía',
          'Callao',
          'Ópera',
          'La Latina',
          'Puerta de Toledo',
          'Acacias',
          'Pirámides',
          'Marqués de Vadillo',
          'Urgel',
          'Oporto',
          'Vista Alegre',
          'Carabanchel',
          'Eugenia de Montijo',
          'Aluche',
          'Empalme',
          'Campamento',
          'Casa de Campo',
        ],
      },
      {
        num: 6,
        inicio: 'Circular',
        fin: 'Circular',
        color: '737f86',
        colorTexto: 'ffffff',
        paradas: [
          'Príncipe Pío',
          'Puerta del Ángel',
          'Alto de Extremadura',
          'Lucero',
          'Laguna',
          'Carpetana',
          'Oporto',
          'Opañel',
          'Plaza Elíptica',
          'Usera',
          'Legazpi',
          'Arganzuela Planetario',
          'Méndez Álvaro',
          'Pacífico',
          'Conde de Casal',
          'Sainz de Baranda',
          'O’Donnell',
          'Manuel Becerra',
          'Diego de León',
          'Av. de América',
          'República Argentina',
          'Nuevos Ministerios',
          'Cuatro Caminos',
          'Guzmán el Bueno',
          'Vicente Aleixandre',
          'Ciudad Universitaria',
          'Moncloa',
          'Argüelles',
        ],
      },
      {
        num: 7,
        inicio: 'Hospital del Henares',
        fin: 'Pitis',
        color: 'f79727',
        colorTexto: 'ffffff',
        paradas: [
          'Hospital del Henares',
          'Henares',
          'Jarama',
          'San Fernando',
          'La Rambla',
          'Coslada Central',
          'Barrio del Puerto',
          'Estadio Metropolitano',
          'Las Musas',
          'San Blas',
          'Simancas',
          'García Noblejas',
          'Ascao',
          'Pueblo Nuevo',
          'Barrio de la Concepción',
          'Parque de las Avenidas',
          'Cartagena',
          'Av. de América',
          'Gregorio Marañón',
          'Alonso Cano',
          'Canal',
          'Islas Filipinas',
          'Guzmán el Bueno',
          'Francos Rodríguez',
          'Valdezarza',
          'Antonio Machado',
          'Peñagrande',
          'Av. de la Ilustración',
          'Lacoma',
          'Arroyofresno',
          'Pitis',
        ],
      },
      {
        num: 8,
        inicio: 'Nuevos Ministerios',
        fin: 'Aeropuerto T4',
        color: 'db74ae',
        colorTexto: 'ffffff',
        paradas: [
          'Nuevos Ministerios',
          'Colombia',
          'Pinar del Rey',
          'Mar de Cristal',
          'Feria de Madrid',
          'Aeropuerto T1-T2-T3',
          'Barajas',
          'Aeropuerto T4',
        ],
      },
      {
        num: 9,
        inicio: 'Paco de Lucía',
        fin: 'Arganda del Rey',
        color: '9c3293',
        colorTexto: 'ffffff',
        paradas: [
          'Paco de Lucía',
          'Mirasierra',
          'Herrera Oria',
          'Barrio del Pilar',
          'Ventilla',
          'Plaza de Castilla',
          'Duque de Pastrana',
          'Pío XII',
          'Colombia',
          'Concha Espina',
          'Cruz del Rayo',
          'Av. de América',
          'Núñez de Balboa',
          'Príncipe de Vergara',
          'Ibiza',
          'Sainz de Baranda',
          'Estrella',
          'Vinateros',
          'Artilleros',
          'Pavones',
          'Valdebernardo',
          'Vicálvaro',
          'San Cipriano',
          'Puerta de Arganda',
          'Rivas-Urbanizaciones',
          'Rivas Futura',
          'Rivas Vaciamadrid',
          'La Poveda',
          'Arganda del Rey',
        ],
      },
      {
        num: 10,
        inicio: 'Hospital Infanta Sofía',
        fin: 'Puerta del Sur',
        color: '015396',
        colorTexto: 'ffffff',
        paradas: [
          'Hospital Infanta Sofía',
          'Reyes Católicos',
          'Baunatal',
          'Manuel de Falla',
          'Marqués de la Valdavia',
          'La Moraleja',
          'La Granja',
          'Ronda de la Comunicación',
          'Las Tablas',
          'Montecarmelo',
          'Tres Olivos',
          'Fuencarral',
          'Begoña',
          'Chamartín',
          'Plaza de Castilla',
          'Cuzco',
          'Santiago Bernabéu',
          'Nuevos Ministerios',
          'Gregorio Marañón',
          'Alonso Martínez',
          'Tribunal',
          'Plaza de España',
          'Príncipe Pío',
          'Lago',
          'Batán',
          'Casa de Campo',
          'Colonia Jardín',
          'Aviación Española',
          'Cuatro Vientos',
          'Joaquín Vilumbrales',
          'Puerta del Sur',
        ],
      },
      {
        num: 11,
        inicio: 'Plaza Elíptica',
        fin: 'La Fortuna',
        color: '00a94e',
        colorTexto: 'ffffff',
        paradas: [
          'Plaza Elíptica',
          'Abrantes',
          'Pan Bendito',
          'San Francisco',
          'Carabanchel Alto',
          'La Peseta',
          'La Fortuna',
        ],
      },
      {
        num: 12,
        inicio: 'MetroSur',
        fin: 'MetroSur',
        color: 'a49901',
        colorTexto: 'ffffff',
        paradas: [
          'Puerta del Sur',
          'Parque Lisboa',
          'AlcorcónCentral',
          'Parque Oeste',
          'Universidad Rey Juan Carlos',
          'Móstoles Central',
          'Pradillo',
          'Hospital de Móstoles',
          'Manuela Malasaña',
          'Loranca',
          'Hospital de Fuenlabrada',
          'Parque Europa',
          'Fuenlabrada Central',
          'Parque de los Estados',
          'Arroyo Culebro',
          'Conservatorio',
          'Alonso de Mendoza',
          'Getafe Central',
          'Juan de la Cierva',
          'El Casar',
          'Los Espartales',
          'El Bercial',
          'El Carrascal',
          'Julián Besteiro',
          'Casa del Reloj',
          'Hospital Severo Ochoa',
          'Leganés Central',
          'San Nicasio',
        ],
      },
    ],
  },
};
