export const METRO_DATA = {
  bilbao: {
    ciudad: 'Bilbao',
    lineas: [
      {
        num: 1,
        inicio: 'Plentzia',
        fin: 'Etxebarri',
        color: 'e74f1e',
        colorTexto: 'ffffff',
        paradas: [
          'Plentzia',
          'Urduliz',
          'Sopela',
          'Larrabasterra',
          'Berango',
          'Ibarbengoa',
          'Bidezabal',
          'Algorta',
          'Aiboa',
          'Neguri',
          'Gobela',
          'Areeta',
          'Lamiako',
          'Leioa',
          'Astrabudua',
          'Erandio',
          'Lutxana',
          'San Ignazio',
          'Sarriko',
          'Deustu',
          'Santimami - San Mamés',
          'Indautxu',
          'Moyua',
          'Abando',
          'Zazpikaleak - Casco Viejo',
          'Santutxu',
          'Basarrate',
          'Bolueta',
          'Etxebarri',
        ],
      },
      {
        num: 2,
        inicio: 'Kabiezes',
        fin: 'Basauri',
        color: '000000',
        colorTexto: 'ffffff',
        paradas: [
          'Kabiezes',
          'Santurtzi',
          'Peñota',
          'Portugalete',
          'Abatxolo',
          'Sestao',
          'Urbinaga',
          'Bagatza',
          'Barakaldo',
          'Ansio',
          'Gurutzeta - Cruces',
          'San Ignazio',
          'Sarriko',
          'Deustu',
          'Santimami - San Mamés',
          'Indautxu',
          'Moyua',
          'Abando',
          'Zazpikaleak - Casco Viejo',
          'Santutxu',
          'Basarrate',
          'Bolueta',
          'Etxebarri',
          'Ariz',
          'Basauri',
        ],
      },
      {
        num: 3,
        inicio: 'Matiko',
        fin: 'Kukullaga',
        color: 'e0007a',
        colorTexto: 'ffffff',
        paradas: [
          'Matiko',
          'Uribarri',
          'Zazpikaleak - Casco Viejo',
          'Zurbaranbarri',
          'Txurdinaga',
          'Otxarkoaga',
          'Kukullaga',
        ],
      },
    ],
  },
  madrid: {
    ciudad: 'Madrid',
    lineas: [
      {
        num: 1,
        inicio: 'Pinar de Chamartín',
        fin: 'Valdecarros',
        color: '2bb6e6',
        colorTexto: 'ffffff',
        paradas: [
          'Pinar de Chamartín',
          'Bambú',
          'Chamartín',
          'Plaza de Castilla',
          'Valdeacederas',
          'Tetuán',
          'Estrecho',
          'Alvarado',
          'Cuatro Caminos',
          'Ríos Rosas',
          'Iglesia',
          'Bilbao',
          'Tribunal',
          'Gran Vía',
          'Sol',
          'Tirso de Molina',
          'Antón Martín',
          'Estación del Arte',
          'Atocha',
          'Menéndez Pelayo',
          'Pacífico',
          'Puente de Vallecas',
          'Nueva Numancia',
          'Portazgo',
          'Buenos Aires',
          'Alto del Arenal',
          'Miguel Hernández',
          'Sierra de Guadalupe',
          'Villa de Vallecas',
          'Congosto',
          'La Gavia',
          'Las Suertes',
          'Valdecarros',
        ],
      },
      {
        num: 2,
        inicio: 'Las Rosas',
        fin: 'Cuatro Caminos',
        color: 'eb2f29',
        colorTexto: 'ffffff',
        paradas: [
          'Las Rosas',
          'Av. de Guadalajara',
          'Alsacia',
          'La Almudena',
          'La Elipa',
          'Ventas',
          'Manuel Becerra',
          'Goya',
          'Príncipe de Vergara',
          'Retiro',
          'Banco de España',
          'Sevilla',
          'Sol',
          'Callao',
          'Santo Domingo',
          'Noviciado',
          'San Bernardo',
          'Quevedo',
          'Canal',
          'Cuatro Caminos',
        ],
      },
      {
        num: 3,
        inicio: 'Villaverde Alto',
        fin: 'Moncloa',
        color: 'fed105',
        colorTexto: '015396',
        paradas: [
          'Villaverde Alto',
          'San Cristóbal',
          'Villaverde Bajo-Cruce',
          'Ciudad de los Ángeles',
          'Ciudad de los Ángeles',
          'Hospital 12 de Octubre',
          'Almendrales',
          'Legazpi',
          'Delicias',
          'Palos de la Frontera',
          'Embajadores',
          'Lavapiés',
          'Sol',
          'Callao',
          'Plaza de España',
          'Ventura Rodríguez',
          'Argüelles',
          'Moncloa',
        ],
      },
      {
        num: 4,
        inicio: 'Argüelles',
        fin: 'Pinar de Chamartín',
        color: 'a15c2f',
        colorTexto: 'ffffff',
        paradas: [
          'Argüelles',
          'San Bernardo',
          'Bilbao',
          'Alonso Martínez',
          'Colón',
          'Serrano',
          'Velázquez',
          'Goya',
          'Lista',
          'Diego de León',
          'Av. de América',
          'Prosperidad',
          'Alfonso XIII',
          'Av. de la Paz',
          'Arturo Soria',
          'Esperanza',
          'Canillas',
          'Mar de Cristal',
          'San Lorenzo',
          'Parque de Santa María',
          'Hortaleza',
          'Manoteras',
          'Pinar de Chamartín',
        ],
      },
      {
        num: 5,
        inicio: 'Alameda de Osuna',
        fin: 'Casa de Campo',
        color: '7ac142',
        colorTexto: 'ffffff',
        paradas: [
          'Alameda de Osuna',
          'El Capricho',
          'Canillejas',
          'Torre Arias',
          'Suanzes',
          'Ciudad Lineal',
          'Pueblo Nuevo',
          'Quintana',
          'El Carmen',
          'Ventas',
          'Diego de León',
          'Núñez de Balboa',
          'Rubén Darío',
          'Alonso Martínez',
          'Chueca',
          'Gran Vía',
          'Callao',
          'Ópera',
          'La Latina',
          'Puerta de Toledo',
          'Acacias',
          'Pirámides',
          'Marqués de Vadillo',
          'Urgel',
          'Oporto',
          'Vista Alegre',
          'Carabanchel',
          'Eugenia de Montijo',
          'Aluche',
          'Empalme',
          'Campamento',
          'Casa de Campo',
        ],
      },
      {
        num: 6,
        inicio: 'Circular',
        fin: 'Circular',
        color: '737f86',
        colorTexto: 'ffffff',
        paradas: [
          'Príncipe Pío',
          'Puerta del Ángel',
          'Alto de Extremadura',
          'Lucero',
          'Laguna',
          'Carpetana',
          'Oporto',
          'Opañel',
          'Plaza Elíptica',
          'Usera',
          'Legazpi',
          'Arganzuela Planetario',
          'Méndez Álvaro',
          'Pacífico',
          'Conde de Casal',
          'Sainz de Baranda',
          'O’Donnell',
          'Manuel Becerra',
          'Diego de León',
          'Av. de América',
          'República Argentina',
          'Nuevos Ministerios',
          'Cuatro Caminos',
          'Guzmán el Bueno',
          'Vicente Aleixandre',
          'Ciudad Universitaria',
          'Moncloa',
          'Argüelles',
        ],
      },
      {
        num: 7,
        inicio: 'Hospital del Henares',
        fin: 'Pitis',
        color: 'f79727',
        colorTexto: 'ffffff',
        paradas: [],
      },
      {
        num: 8,
        inicio: 'Nuevos Ministerios',
        fin: 'Aeropuerto T4',
        color: 'db74ae',
        colorTexto: 'ffffff',
        paradas: [],
      },
      {
        num: 9,
        inicio: 'Paco de Lucía',
        fin: 'Arganda del Rey',
        color: '9c3293',
        colorTexto: 'ffffff',
        paradas: [],
      },
      {
        num: 10,
        inicio: 'Hospital Infanta Sofía',
        fin: 'Puerta del Sur',
        color: '015396',
        colorTexto: 'ffffff',
        paradas: [],
      },
      {
        num: 11,
        inicio: 'Plaza Elíptica',
        fin: 'La Fortuna',
        color: '00a94e',
        colorTexto: 'ffffff',
        paradas: [],
      },
      {
        num: 12,
        inicio: 'MetroSur',
        fin: 'MetroSur',
        color: 'a49901',
        colorTexto: 'ffffff',
        paradas: [],
      },
    ],
  },
};
