import { RenfeLineaInterface } from '@interfaces/renfe.interfaces';

export const RENFE_DATA: RenfeLineaInterface[] = [
  {
    id: 'c1',
    nombre: 'C-1 Santurtzi / Bilbao Abando',
    color: '#fc3442',
    paradas: [
      'Bilbao Abando',
      'Zabalburu',
      'Ametzola',
      'Autonomía',
      'San Mamés',
      'Olabeaga',
      'Zorrotza',
      'Lutxana',
      'Barakaldo',
      'Sestao',
      'La Iberia',
      'Portugalete',
      'Peñota',
      'Santurtzi',
    ],
  },
  {
    id: 'c2',
    nombre: 'C-2 Muskiz / Bilbao Abando',
    color: '#079531',
    paradas: [
      'Bilbao Abando',
      'Zabalburu',
      'Ametzola',
      'Autonomía',
      'San Mamés',
      'Olabeaga',
      'Zorrotza',
      'Lutxana',
      'Barakaldo',
      'Galindo',
      'Trápaga',
      'Trapagaran',
      'Urioste',
      'Sagrada Familia',
      'Ortuella',
      'Gallarta',
      'Putxeta',
      'Muskiz',
    ],
  },
  {
    id: 'c3',
    nombre: 'C-3 Orduña / Bilbao Abando',
    color: '#00abe7',
    paradas: [
      'Bilbao Abando',
      'Miribilla',
      'La Peña',
      'Ollargan',
      'Bidebieta - Basauri',
      'Abaroa - San Miguel',
      'Basauri',
      'Arrigorriaga',
      'Ugao - Miraballes',
      'Bakiola',
      'Arrankudiaga',
      'Arbide',
      'Arakaldo',
      'Areta',
      'Llodio',
      'Sta. Cruz de Llodio',
      'Luiaondo',
      'Salbio',
      'Amurrio Iparralde',
      'Amurrio',
      'Iñarratxu',
      'Orduña',
    ],
  },
  {
    id: 'c4',
    nombre: 'C-4 Bilbao La Concordia / La Calzada',
    color: '#af4298',
    paradas: [
      'Bilbao La Concordia',
      'Ametzola',
      ' Basurto Hospital',
      'Zorrotza zorrozgoiti',
      'Santa Agueda',
      'Kastrexana',
      'Irauregi',
      'Zaramillo',
      'La Quadra',
      'Sodupe',
      'Artxube',
      'Lambarri',
      'Güeñes',
      'Aranguren',
      'Aranguren Apdo',
      'Zalla',
      'Colegio',
      'Ibarra',
      'La Herrera',
      'Balmaseda',
      'La Calzada',
    ],
  },
];
