import {
  KlaseaInterface,
  TxartelMotaInterface,
} from '@interfaces/txartelak.interfaces';

export const UMEAK_DATA: KlaseaInterface[] = [
  {
    norena: 'Eneko',
    umeak: [
      { id: 1, izena: 'Adrian', argazkia: 'eneko/adrian' },
      { id: 2, izena: 'Ager', argazkia: 'eneko/ager' },
      { id: 3, izena: 'Aimar', argazkia: 'eneko/aimar' },
      { id: 4, izena: 'Ander Xabier', argazkia: 'eneko/ander-xabier' },
      { id: 5, izena: 'Aratz', argazkia: 'eneko/aratz' },
      { id: 6, izena: 'Arya', argazkia: 'eneko/arya' },
      { id: 7, izena: 'Beñat', argazkia: 'eneko/benat' },
      { id: 8, izena: 'Eider', argazkia: 'eneko/eider' },
      { id: 9, izena: 'Eneko', argazkia: 'eneko/eneko' },
      { id: 10, izena: 'Enetz', argazkia: 'eneko/enetz' },
      { id: 11, izena: 'Harri', argazkia: 'eneko/harri' },
      { id: 12, izena: 'Hodei', argazkia: 'eneko/hodei' },
      { id: 13, izena: 'Irati', argazkia: 'eneko/irati' },
      { id: 14, izena: 'Izadi', argazkia: 'eneko/izadi' },
      { id: 15, izena: 'Izane', argazkia: 'eneko/izane' },
      { id: 16, izena: 'Izare', argazkia: 'eneko/izare' },
      { id: 17, izena: 'Jare', argazkia: 'eneko/jare' },
      { id: 18, izena: 'Joaquin', argazkia: 'eneko/joaquin' },
      { id: 19, izena: 'Julen', argazkia: 'eneko/julen' },
      { id: 20, izena: 'Luken', argazkia: 'eneko/luken' },
      { id: 21, izena: 'Maialen', argazkia: 'eneko/maialen' },
      { id: 22, izena: 'Malen', argazkia: 'eneko/malen' },
      { id: 23, izena: 'Mikel', argazkia: 'eneko/mikel' },
      { id: 24, izena: 'Nahia', argazkia: 'eneko/nahia' },
      { id: 25, izena: 'Ninbe', argazkia: 'eneko/ninbe' },
      { id: 26, izena: 'Paul', argazkia: 'eneko/paul' },
    ],
  },
  {
    norena: 'Unai',
    umeak: [
      { id: 27, izena: 'Aiora', argazkia: 'unai/aiora' },
      { id: 28, izena: 'Aiur', argazkia: 'unai/aiur' },
      { id: 29, izena: 'Alaia', argazkia: 'unai/alaia' },
      { id: 30, izena: 'Amets', argazkia: 'unai/amets' },
      { id: 31, izena: 'Ane', argazkia: 'unai/ane' },
      { id: 32, izena: 'Ariane', argazkia: 'unai/ariane' },
      { id: 33, izena: 'Ekia', argazkia: 'unai/ekia' },
      { id: 34, izena: 'Enara', argazkia: 'unai/enara' },
      { id: 35, izena: 'Enzo', argazkia: 'unai/enzo' },
      { id: 36, izena: 'Euken', argazkia: 'unai/euken' },
      { id: 37, izena: 'Haizea', argazkia: 'unai/haizea' },
      { id: 38, izena: 'Inari', argazkia: 'unai/inari' },
      { id: 39, izena: 'Jon', argazkia: 'unai/jon' },
      { id: 40, izena: 'June', argazkia: 'unai/june' },
      { id: 41, izena: 'Katixa', argazkia: 'unai/katixa' },
      { id: 42, izena: 'Lier', argazkia: 'unai/lier' },
      { id: 43, izena: 'Markel', argazkia: 'unai/markel' },
      { id: 44, izena: 'Martina', argazkia: 'unai/martina' },
      { id: 45, izena: 'Naia', argazkia: 'unai/naia' },
      { id: 46, izena: 'Oier', argazkia: 'unai/oier' },
      { id: 47, izena: 'Oinatz', argazkia: 'unai/oinatz' },
      { id: 48, izena: 'Roke', argazkia: 'unai/roke' },
      { id: 49, izena: 'Unai', argazkia: 'unai/unai' },
      { id: 50, izena: 'Unax', argazkia: 'unai/unax' },
      { id: 51, izena: 'Xabier', argazkia: 'unai/xabier' },
    ],
  },
];

export const TXARTELAK_DATA: TxartelMotaInterface[] = [
  { id: 1, mota: 'Barik', argazkia: 'barik' },
  { id: 2, mota: 'Bat', argazkia: 'bat' },
  { id: 3, mota: 'Mugi', argazkia: 'mugi' },
];
